### ISSUE TITLE
Multiple NameErrors

### ISSUE THREAD

**Issue by gaetgu** [DiamondsBattle/Collider#1]
On _**pop!_OS**_ latest.

Running `window.py` results in a larger error once a gamemode is selected.

```console
Traceback (most recent call last):
  File "/home/gabriel/.local/lib/python3.8/site-packages/direct/showbase/EventManager.py", line 49, in eventLoopTask
    self.doEvents()
  File "/home/gabriel/.local/lib/python3.8/site-packages/direct/showbase/EventManager.py", line 43, in doEvents
    processFunc(dequeueFunc())
  File "/home/gabriel/.local/lib/python3.8/site-packages/direct/showbase/EventManager.py", line 99, in processEvent
    messenger.send(eventName, paramList)
  File "/home/gabriel/.local/lib/python3.8/site-packages/direct/showbase/Messenger.py", line 337, in send
    self.__dispatch(acceptorDict, event, sentArgs, foundWatch)
  File "/home/gabriel/.local/lib/python3.8/site-packages/direct/showbase/Messenger.py", line 422, in __dispatch
    result = method (*(extraArgs + sentArgs))
  File "/home/gabriel/.local/lib/python3.8/site-packages/ursina/main.py", line 173, in input
    __main__.input(key)
  File "window.py", line 41, in input
    shoot_test()
NameError: name 'shoot_test' is not defined
:task(error): Exception occurred in PythonTask eventManager
Traceback (most recent call last):
  File "window.py", line 113, in <module>
    app.run()
  File "/home/gabriel/.local/lib/python3.8/site-packages/ursina/main.py", line 227, in run
    super().run()
  File "/home/gabriel/.local/lib/python3.8/site-packages/direct/showbase/ShowBase.py", line 3319, in run
    self.taskMgr.run()
  File "/home/gabriel/.local/lib/python3.8/site-packages/direct/task/Task.py", line 541, in run
    self.step()
  File "/home/gabriel/.local/lib/python3.8/site-packages/direct/task/Task.py", line 495, in step
    self.mgr.poll()
  File "/home/gabriel/.local/lib/python3.8/site-packages/direct/showbase/EventManager.py", line 49, in eventLoopTask
    self.doEvents()
  File "/home/gabriel/.local/lib/python3.8/site-packages/direct/showbase/EventManager.py", line 43, in doEvents
    processFunc(dequeueFunc())
  File "/home/gabriel/.local/lib/python3.8/site-packages/direct/showbase/EventManager.py", line 99, in processEvent
    messenger.send(eventName, paramList)
  File "/home/gabriel/.local/lib/python3.8/site-packages/direct/showbase/Messenger.py", line 337, in send
    self.__dispatch(acceptorDict, event, sentArgs, foundWatch)
  File "/home/gabriel/.local/lib/python3.8/site-packages/direct/showbase/Messenger.py", line 422, in __dispatch
    result = method (*(extraArgs + sentArgs))
  File "/home/gabriel/.local/lib/python3.8/site-packages/ursina/main.py", line 173, in input
    __main__.input(key)
  File "window.py", line 41, in input
    shoot_test()
NameError: name 'shoot_test' is not defined
```

**Comment by DiamondsBattle** [comment]
Fixed, commented the unused statements.
